name: Sync main branch to upstream-changes branch
on:
  push:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "emdeh-cyber@proton.me"
          git config --global user.name "emdeh"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch upstream-changes branch
        run: git fetch origin upstream-changes

      - name: Reset upstream-changes branch to match main
        run: |
          git checkout upstream-changes
          git reset --hard origin/main

      - name: Push changes to upstream-changes
        run: git push --force origin upstream-changes
