name: Sync main branch to upstream-changes branch
on:
  push:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.email "emdeh-cyber@proton.me"
          git config --global user.name "emdeh"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch upstream-changes branch
        run: git fetch origin upstream-changes

      - name: Checkout upstream-changes branch
        run: git checkout -b upstream-changes origin/upstream-changes

      - name: Merge changes from main into upstream-changes
        run: |
          git pull origin main --force-with-lease
          git push origin upstream-changes
