name: Sync main branch to upstream-changes branch
on:
  push:
    branches:
      - main

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch upstream-changes branch
        run: git fetch origin upstream-changes

      - name: Checkout upstream-changes branch
        run: git checkout -b upstream-changes origin/upstream-changes

      - name: Merge changes from main into upstream-changes
        run: |
          git merge --strategy-option theirs main
          git push origin upstream-changes
